<?php

use App\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

    	$countries = array(
    		array('id' => 1,'code' => 'AF' ,'country' => "Afghanistan",'phone_code' => 93),
    		array('id' => 2,'code' => 'AL' ,'country' => "Albania",'phone_code' => 355),
    		array('id' => 3,'code' => 'DZ' ,'country' => "Algeria",'phone_code' => 213),
    		array('id' => 4,'code' => 'AS' ,'country' => "American Samoa",'phone_code' => 1684),
    		array('id' => 5,'code' => 'AD' ,'country' => "Andorra",'phone_code' => 376),
    		array('id' => 6,'code' => 'AO' ,'country' => "Angola",'phone_code' => 244),
    		array('id' => 7,'code' => 'AI' ,'country' => "Anguilla",'phone_code' => 1264),
    		array('id' => 8,'code' => 'AQ' ,'country' => "Antarctica",'phone_code' => 0),
    		array('id' => 9,'code' => 'AG' ,'country' => "Antigua And Barbuda",'phone_code' => 1268),
    		array('id' => 10,'code' => 'AR','country' => "Argentina",'phone_code' => 54),
    		array('id' => 11,'code' => 'AM','country' => "Armenia",'phone_code' => 374),
    		array('id' => 12,'code' => 'AW','country' => "Aruba",'phone_code' => 297),
    		array('id' => 13,'code' => 'AU','country' => "Australia",'phone_code' => 61),
    		array('id' => 14,'code' => 'AT','country' => "Austria",'phone_code' => 43),
    		array('id' => 15,'code' => 'AZ','country' => "Azerbaijan",'phone_code' => 994),
    		array('id' => 16,'code' => 'BS','country' => "Bahamas The",'phone_code' => 1242),
    		array('id' => 17,'code' => 'BH','country' => "Bahrain",'phone_code' => 973),
    		array('id' => 18,'code' => 'BD','country' => "Bangladesh",'phone_code' => 880),
    		array('id' => 19,'code' => 'BB','country' => "Barbados",'phone_code' => 1246),
    		array('id' => 20,'code' => 'BY','country' => "Belarus",'phone_code' => 375),
    		array('id' => 21,'code' => 'BE','country' => "Belgium",'phone_code' => 32),
    		array('id' => 22,'code' => 'BZ','country' => "Belize",'phone_code' => 501),
    		array('id' => 23,'code' => 'BJ','country' => "Benin",'phone_code' => 229),
    		array('id' => 24,'code' => 'BM','country' => "Bermuda",'phone_code' => 1441),
    		array('id' => 25,'code' => 'BT','country' => "Bhutan",'phone_code' => 975),
    		array('id' => 26,'code' => 'BO','country' => "Bolivia",'phone_code' => 591),
    		array('id' => 27,'code' => 'BA','country' => "Bosnia and Herzegovina",'phone_code' => 387),
    		array('id' => 28,'code' => 'BW','country' => "Botswana",'phone_code' => 267),
    		array('id' => 29,'code' => 'BV','country' => "Bouvet Island",'phone_code' => 0),
    		array('id' => 30,'code' => 'BR','country' => "Brazil",'phone_code' => 55),
    		array('id' => 31,'code' => 'IO','country' => "British Indian Ocean Territory",'phone_code' => 246),
    		array('id' => 32,'code' => 'BN','country' => "Brunei",'phone_code' => 673),
    		array('id' => 33,'code' => 'BG','country' => "Bulgaria",'phone_code' => 359),
    		array('id' => 34,'code' => 'BF','country' => "Burkina Faso",'phone_code' => 226),
    		array('id' => 35,'code' => 'BI','country' => "Burundi",'phone_code' => 257),
    		array('id' => 36,'code' => 'KH','country' => "Cambodia",'phone_code' => 855),
    		array('id' => 37,'code' => 'CM','country' => "Cameroon",'phone_code' => 237),
    		array('id' => 38,'code' => 'CA','country' => "Canada",'phone_code' => 1),
    		array('id' => 39,'code' => 'CV','country' => "Cape Verde",'phone_code' => 238),
    		array('id' => 40,'code' => 'KY','country' => "Cayman Islands",'phone_code' => 1345),
    		array('id' => 41,'code' => 'CF','country' => "Central African Republic",'phone_code' => 236),
    		array('id' => 42,'code' => 'TD','country' => "Chad",'phone_code' => 235),
    		array('id' => 43,'code' => 'CL','country' => "Chile",'phone_code' => 56),
    		array('id' => 44,'code' => 'CN','country' => "China",'phone_code' => 86),
    		array('id' => 45,'code' => 'CX','country' => "Christmas Island",'phone_code' => 61),
    		array('id' => 46,'code' => 'CC','country' => "Cocos (Keeling) Islands",'phone_code' => 672),
    		array('id' => 47,'code' => 'CO','country' => "Colombia",'phone_code' => 57),
    		array('id' => 48,'code' => 'KM','country' => "Comoros",'phone_code' => 269),
    		array('id' => 49,'code' => 'CG','country' => "Congo",'phone_code' => 242),
    		array('id' => 50,'code' => 'CD','country' => "Congo The Democratic Republic Of The",'phone_code' => 242),
    		array('id' => 51,'code' => 'CK','country' => "Cook Islands",'phone_code' => 682),
    		array('id' => 52,'code' => 'CR','country' => "Costa Rica",'phone_code' => 506),
    		array('id' => 53,'code' => 'CI','country' => "Cote D Ivoire (Ivory Coast)",'phone_code' => 225),
    		array('id' => 54,'code' => 'HR','country' => "Croatia (Hrvatska)",'phone_code' => 385),
    		array('id' => 55,'code' => 'CU','country' => "Cuba",'phone_code' => 53),
    		array('id' => 56,'code' => 'CY','country' => "Cyprus",'phone_code' => 357),
    		array('id' => 57,'code' => 'CZ','country' => "Czech Republic",'phone_code' => 420),
    		array('id' => 58,'code' => 'DK','country' => "Denmark",'phone_code' => 45),
    		array('id' => 59,'code' => 'DJ','country' => "Djibouti",'phone_code' => 253),
    		array('id' => 60,'code' => 'DM','country' => "Dominica",'phone_code' => 1767),
    		array('id' => 61,'code' => 'DO','country' => "Dominican Republic",'phone_code' => 1809),
    		array('id' => 62,'code' => 'TP','country' => "East Timor",'phone_code' => 670),
    		array('id' => 63,'code' => 'EC','country' => "Ecuador",'phone_code' => 593),
    		array('id' => 64,'code' => 'EG','country' => "Egypt",'phone_code' => 20),
    		array('id' => 65,'code' => 'SV','country' => "El Salvador",'phone_code' => 503),
    		array('id' => 66,'code' => 'GQ','country' => "Equatorial Guinea",'phone_code' => 240),
    		array('id' => 67,'code' => 'ER','country' => "Eritrea",'phone_code' => 291),
    		array('id' => 68,'code' => 'EE','country' => "Estonia",'phone_code' => 372),
    		array('id' => 69,'code' => 'ET','country' => "Ethiopia",'phone_code' => 251),
    		array('id' => 70,'code' => 'XA','country' => "External Territories of Australia",'phone_code' => 61),
    		array('id' => 71,'code' => 'FK','country' => "Falkland Islands",'phone_code' => 500),
    		array('id' => 72,'code' => 'FO','country' => "Faroe Islands",'phone_code' => 298),
    		array('id' => 73,'code' => 'FJ','country' => "Fiji Islands",'phone_code' => 679),
    		array('id' => 74,'code' => 'FI','country' => "Finland",'phone_code' => 358),
    		array('id' => 75,'code' => 'FR','country' => "France",'phone_code' => 33),
    		array('id' => 76,'code' => 'GF','country' => "French Guiana",'phone_code' => 594),
    		array('id' => 77,'code' => 'PF','country' => "French Polynesia",'phone_code' => 689),
    		array('id' => 78,'code' => 'TF','country' => "French Southern Territories",'phone_code' => 0),
    		array('id' => 79,'code' => 'GA','country' => "Gabon",'phone_code' => 241),
    		array('id' => 80,'code' => 'GM','country' => "Gambia The",'phone_code' => 220),
    		array('id' => 81,'code' => 'GE','country' => "Georgia",'phone_code' => 995),
    		array('id' => 82,'code' => 'DE','country' => "Germany",'phone_code' => 49),
    		array('id' => 83,'code' => 'GH','country' => "Ghana",'phone_code' => 233),
    		array('id' => 84,'code' => 'GI','country' => "Gibraltar",'phone_code' => 350),
    		array('id' => 85,'code' => 'GR','country' => "Greece",'phone_code' => 30),
    		array('id' => 86,'code' => 'GL','country' => "Greenland",'phone_code' => 299),
    		array('id' => 87,'code' => 'GD','country' => "Grenada",'phone_code' => 1473),
    		array('id' => 88,'code' => 'GP','country' => "Guadeloupe",'phone_code' => 590),
    		array('id' => 89,'code' => 'GU','country' => "Guam",'phone_code' => 1671),
    		array('id' => 90,'code' => 'GT','country' => "Guatemala",'phone_code' => 502),
    		array('id' => 91,'code' => 'XU','country' => "Guernsey and Alderney",'phone_code' => 44),
    		array('id' => 92,'code' => 'GN','country' => "Guinea",'phone_code' => 224),
    		array('id' => 93,'code' => 'GW','country' => "Guinea-Bissau",'phone_code' => 245),
    		array('id' => 94,'code' => 'GY','country' => "Guyana",'phone_code' => 592),
    		array('id' => 95,'code' => 'HT','country' => "Haiti",'phone_code' => 509),
    		array('id' => 96,'code' => 'HM','country' => "Heard and McDonald Islands",'phone_code' => 0),
    		array('id' => 97,'code' => 'HN','country' => "Honduras",'phone_code' => 504),
    		array('id' => 98,'code' => 'HK','country' => "Hong Kong S.A.R.",'phone_code' => 852),
    		array('id' => 99,'code' => 'HU','country' => "Hungary",'phone_code' => 36),
    		array('id' => 100,'code' => 'IS','country' => "Iceland",'phone_code' => 354),
    		array('id' => 101,'code' => 'IN','country' => "India",'phone_code' => 91),
    		array('id' => 102,'code' => 'ID','country' => "Indonesia",'phone_code' => 62),
    		array('id' => 103,'code' => 'IR','country' => "Iran",'phone_code' => 98),
    		array('id' => 104,'code' => 'IQ','country' => "Iraq",'phone_code' => 964),
    		array('id' => 105,'code' => 'IE','country' => "Ireland",'phone_code' => 353),
    		array('id' => 106,'code' => 'IL','country' => "Israel",'phone_code' => 972),
    		array('id' => 107,'code' => 'IT','country' => "Italy",'phone_code' => 39),
    		array('id' => 108,'code' => 'JM','country' => "Jamaica",'phone_code' => 1876),
    		array('id' => 109,'code' => 'JP','country' => "Japan",'phone_code' => 81),
    		array('id' => 110,'code' => 'XJ','country' => "Jersey",'phone_code' => 44),
    		array('id' => 111,'code' => 'JO','country' => "Jordan",'phone_code' => 962),
    		array('id' => 112,'code' => 'KZ','country' => "Kazakhstan",'phone_code' => 7),
    		array('id' => 113,'code' => 'KE','country' => "Kenya",'phone_code' => 254),
    		array('id' => 114,'code' => 'KI','country' => "Kiribati",'phone_code' => 686),
    		array('id' => 115,'code' => 'KP','country' => "Korea North",'phone_code' => 850),
    		array('id' => 116,'code' => 'KR','country' => "Korea South",'phone_code' => 82),
    		array('id' => 117,'code' => 'KW','country' => "Kuwait",'phone_code' => 965),
    		array('id' => 118,'code' => 'KG','country' => "Kyrgyzstan",'phone_code' => 996),
    		array('id' => 119,'code' => 'LA','country' => "Laos",'phone_code' => 856),
    		array('id' => 120,'code' => 'LV','country' => "Latvia",'phone_code' => 371),
    		array('id' => 121,'code' => 'LB','country' => "Lebanon",'phone_code' => 961),
    		array('id' => 122,'code' => 'LS','country' => "Lesotho",'phone_code' => 266),
    		array('id' => 123,'code' => 'LR','country' => "Liberia",'phone_code' => 231),
    		array('id' => 124,'code' => 'LY','country' => "Libya",'phone_code' => 218),
    		array('id' => 125,'code' => 'LI','country' => "Liechtenstein",'phone_code' => 423),
    		array('id' => 126,'code' => 'LT','country' => "Lithuania",'phone_code' => 370),
    		array('id' => 127,'code' => 'LU','country' => "Luxembourg",'phone_code' => 352),
    		array('id' => 128,'code' => 'MO','country' => "Macau S.A.R.",'phone_code' => 853),
    		array('id' => 129,'code' => 'MK','country' => "Macedonia",'phone_code' => 389),
    		array('id' => 130,'code' => 'MG','country' => "Madagascar",'phone_code' => 261),
    		array('id' => 131,'code' => 'MW','country' => "Malawi",'phone_code' => 265),
    		array('id' => 132,'code' => 'MY','country' => "Malaysia",'phone_code' => 60),
    		array('id' => 133,'code' => 'MV','country' => "Maldives",'phone_code' => 960),
    		array('id' => 134,'code' => 'ML','country' => "Mali",'phone_code' => 223),
    		array('id' => 135,'code' => 'MT','country' => "Malta",'phone_code' => 356),
    		array('id' => 136,'code' => 'XM','country' => "Man (Isle of)",'phone_code' => 44),
    		array('id' => 137,'code' => 'MH','country' => "Marshall Islands",'phone_code' => 692),
    		array('id' => 138,'code' => 'MQ','country' => "Martinique",'phone_code' => 596),
    		array('id' => 139,'code' => 'MR','country' => "Mauritania",'phone_code' => 222),
    		array('id' => 140,'code' => 'MU','country' => "Mauritius",'phone_code' => 230),
    		array('id' => 141,'code' => 'YT','country' => "Mayotte",'phone_code' => 269),
    		array('id' => 142,'code' => 'MX','country' => "Mexico",'phone_code' => 52),
    		array('id' => 143,'code' => 'FM','country' => "Micronesia",'phone_code' => 691),
    		array('id' => 144,'code' => 'MD','country' => "Moldova",'phone_code' => 373),
    		array('id' => 145,'code' => 'MC','country' => "Monaco",'phone_code' => 377),
    		array('id' => 146,'code' => 'MN','country' => "Mongolia",'phone_code' => 976),
    		array('id' => 147,'code' => 'MS','country' => "Montserrat",'phone_code' => 1664),
    		array('id' => 148,'code' => 'MA','country' => "Morocco",'phone_code' => 212),
    		array('id' => 149,'code' => 'MZ','country' => "Mozambique",'phone_code' => 258),
    		array('id' => 150,'code' => 'MM','country' => "Myanmar",'phone_code' => 95),
    		array('id' => 151,'code' => 'NA','country' => "Namibia",'phone_code' => 264),
    		array('id' => 152,'code' => 'NR','country' => "Nauru",'phone_code' => 674),
    		array('id' => 153,'code' => 'NP','country' => "Nepal",'phone_code' => 977),
    		array('id' => 154,'code' => 'AN','country' => "Netherlands Antilles",'phone_code' => 599),
    		array('id' => 155,'code' => 'NL','country' => "Netherlands The",'phone_code' => 31),
    		array('id' => 156,'code' => 'NC','country' => "New Caledonia",'phone_code' => 687),
    		array('id' => 157,'code' => 'NZ','country' => "New Zealand",'phone_code' => 64),
    		array('id' => 158,'code' => 'NI','country' => "Nicaragua",'phone_code' => 505),
    		array('id' => 159,'code' => 'NE','country' => "Niger",'phone_code' => 227),
    		array('id' => 160,'code' => 'NG','country' => "Nigeria",'phone_code' => 234),
    		array('id' => 161,'code' => 'NU','country' => "Niue",'phone_code' => 683),
    		array('id' => 162,'code' => 'NF','country' => "Norfolk Island",'phone_code' => 672),
    		array('id' => 163,'code' => 'MP','country' => "Northern Mariana Islands",'phone_code' => 1670),
    		array('id' => 164,'code' => 'NO','country' => "Norway",'phone_code' => 47),
    		array('id' => 165,'code' => 'OM','country' => "Oman",'phone_code' => 968),
    		array('id' => 166,'code' => 'PK','country' => "Pakistan",'phone_code' => 92),
    		array('id' => 167,'code' => 'PW','country' => "Palau",'phone_code' => 680),
    		array('id' => 168,'code' => 'PS','country' => "Palestinian Territory Occupied",'phone_code' => 970),
    		array('id' => 169,'code' => 'PA','country' => "Panama",'phone_code' => 507),
    		array('id' => 170,'code' => 'PG','country' => "Papua new Guinea",'phone_code' => 675),
    		array('id' => 171,'code' => 'PY','country' => "Paraguay",'phone_code' => 595),
    		array('id' => 172,'code' => 'PE','country' => "Peru",'phone_code' => 51),
    		array('id' => 173,'code' => 'PH','country' => "Philippines",'phone_code' => 63),
    		array('id' => 174,'code' => 'PN','country' => "Pitcairn Island",'phone_code' => 0),
    		array('id' => 175,'code' => 'PL','country' => "Poland",'phone_code' => 48),
    		array('id' => 176,'code' => 'PT','country' => "Portugal",'phone_code' => 351),
    		array('id' => 177,'code' => 'PR','country' => "Puerto Rico",'phone_code' => 1787),
    		array('id' => 178,'code' => 'QA','country' => "Qatar",'phone_code' => 974),
    		array('id' => 179,'code' => 'RE','country' => "Reunion",'phone_code' => 262),
    		array('id' => 180,'code' => 'RO','country' => "Romania",'phone_code' => 40),
    		array('id' => 181,'code' => 'RU','country' => "Russia",'phone_code' => 70),
    		array('id' => 182,'code' => 'RW','country' => "Rwanda",'phone_code' => 250),
    		array('id' => 183,'code' => 'SH','country' => "Saint Helena",'phone_code' => 290),
    		array('id' => 184,'code' => 'KN','country' => "Saint Kitts And Nevis",'phone_code' => 1869),
    		array('id' => 185,'code' => 'LC','country' => "Saint Lucia",'phone_code' => 1758),
    		array('id' => 186,'code' => 'PM','country' => "Saint Pierre and Miquelon",'phone_code' => 508),
    		array('id' => 187,'code' => 'VC','country' => "Saint Vincent And The Grenadines",'phone_code' => 1784),
    		array('id' => 188,'code' => 'WS','country' => "Samoa",'phone_code' => 684),
    		array('id' => 189,'code' => 'SM','country' => "San Marino",'phone_code' => 378),
    		array('id' => 190,'code' => 'ST','country' => "Sao Tome and Principe",'phone_code' => 239),
    		array('id' => 191,'code' => 'SA','country' => "Saudi Arabia",'phone_code' => 966),
    		array('id' => 192,'code' => 'SN','country' => "Senegal",'phone_code' => 221),
    		array('id' => 193,'code' => 'RS','country' => "Serbia",'phone_code' => 381),
    		array('id' => 194,'code' => 'SC','country' => "Seychelles",'phone_code' => 248),
    		array('id' => 195,'code' => 'SL','country' => "Sierra Leone",'phone_code' => 232),
    		array('id' => 196,'code' => 'SG','country' => "Singapore",'phone_code' => 65),
    		array('id' => 197,'code' => 'SK','country' => "Slovakia",'phone_code' => 421),
    		array('id' => 198,'code' => 'SI','country' => "Slovenia",'phone_code' => 386),
    		array('id' => 199,'code' => 'XG','country' => "Smaller Territories of the UK",'phone_code' => 44),
    		array('id' => 200,'code' => 'SB','country' => "Solomon Islands",'phone_code' => 677),
    		array('id' => 201,'code' => 'SO','country' => "Somalia",'phone_code' => 252),
    		array('id' => 202,'code' => 'ZA','country' => "South Africa",'phone_code' => 27),
    		array('id' => 203,'code' => 'GS','country' => "South Georgia",'phone_code' => 0),
    		array('id' => 204,'code' => 'SS','country' => "South Sudan",'phone_code' => 211),
    		array('id' => 205,'code' => 'ES','country' => "Spain",'phone_code' => 34),
    		array('id' => 206,'code' => 'LK','country' => "Sri Lanka",'phone_code' => 94),
    		array('id' => 207,'code' => 'SD','country' => "Sudan",'phone_code' => 249),
    		array('id' => 208,'code' => 'SR','country' => "Suriname",'phone_code' => 597),
    		array('id' => 209,'code' => 'SJ','country' => "Svalbard And Jan Mayen Islands",'phone_code' => 47),
    		array('id' => 210,'code' => 'SZ','country' => "Swaziland",'phone_code' => 268),
    		array('id' => 211,'code' => 'SE','country' => "Sweden",'phone_code' => 46),
    		array('id' => 212,'code' => 'CH','country' => "Switzerland",'phone_code' => 41),
    		array('id' => 213,'code' => 'SY','country' => "Syria",'phone_code' => 963),
    		array('id' => 214,'code' => 'TW','country' => "Taiwan",'phone_code' => 886),
    		array('id' => 215,'code' => 'TJ','country' => "Tajikistan",'phone_code' => 992),
    		array('id' => 216,'code' => 'TZ','country' => "Tanzania",'phone_code' => 255),
    		array('id' => 217,'code' => 'TH','country' => "Thailand",'phone_code' => 66),
    		array('id' => 218,'code' => 'TG','country' => "Togo",'phone_code' => 228),
    		array('id' => 219,'code' => 'TK','country' => "Tokelau",'phone_code' => 690),
    		array('id' => 220,'code' => 'TO','country' => "Tonga",'phone_code' => 676),
    		array('id' => 221,'code' => 'TT','country' => "Trinidad And Tobago",'phone_code' => 1868),
    		array('id' => 222,'code' => 'TN','country' => "Tunisia",'phone_code' => 216),
    		array('id' => 223,'code' => 'TR','country' => "Turkey",'phone_code' => 90),
    		array('id' => 224,'code' => 'TM','country' => "Turkmenistan",'phone_code' => 7370),
    		array('id' => 225,'code' => 'TC','country' => "Turks And Caicos Islands",'phone_code' => 1649),
    		array('id' => 226,'code' => 'TV','country' => "Tuvalu",'phone_code' => 688),
    		array('id' => 227,'code' => 'UG','country' => "Uganda",'phone_code' => 256),
    		array('id' => 228,'code' => 'UA','country' => "Ukraine",'phone_code' => 380),
    		array('id' => 229,'code' => 'AE','country' => "United Arab Emirates",'phone_code' => 971),
    		array('id' => 230,'code' => 'GB','country' => "United Kingdom",'phone_code' => 44),
    		array('id' => 231,'code' => 'US','country' => "United States",'phone_code' => 1),
    		array('id' => 232,'code' => 'UM','country' => "United States Minor Outlying Islands",'phone_code' => 1),
    		array('id' => 233,'code' => 'UY','country' => "Uruguay",'phone_code' => 598),
    		array('id' => 234,'code' => 'UZ','country' => "Uzbekistan",'phone_code' => 998),
    		array('id' => 235,'code' => 'VU','country' => "Vanuatu",'phone_code' => 678),
    		array('id' => 236,'code' => 'VA','country' => "Vatican City State (Holy See)",'phone_code' => 39),
    		array('id' => 237,'code' => 'VE','country' => "Venezuela",'phone_code' => 58),
    		array('id' => 238,'code' => 'VN','country' => "Vietnam",'phone_code' => 84),
    		array('id' => 239,'code' => 'VG','country' => "Virgin Islands (British)",'phone_code' => 1284),
    		array('id' => 240,'code' => 'VI','country' => "Virgin Islands (US)",'phone_code' => 1340),
    		array('id' => 241,'code' => 'WF','country' => "Wallis And Futuna Islands",'phone_code' => 681),
    		array('id' => 242,'code' => 'EH','country' => "Western Sahara",'phone_code' => 212),
    		array('id' => 243,'code' => 'YE','country' => "Yemen",'phone_code' => 967),
    		array('id' => 244,'code' => 'YU','country' => "Yugoslavia",'phone_code' => 38),
    		array('id' => 245,'code' => 'ZM','country' => "Zambia",'phone_code' => 260),
    		array('id' => 246,'code' => 'ZW','country' => "Zimbabwe",'phone_code' => 263),
    	);

		DB::table('countries')->insert($countries);
    }
}
